var score;
score = 100;
console.log("Your score was " + score);
console.log("Great splat!!!");
score = score + 50;
console.log("New score: " + score);
console.log("Way to go!");
console.log("You successfully splatted a kumquat!");
score = score + 100;
console.log("Updated score: " + score);
console.log("Congratulations! Keep up the great work!");